### ISSUE TITLE
// Shield lore

### ISSUE THREAD

**Issue by Feelzor** [FishingCactus/NanotaleEarlyAccessBugs#128] opened 2020-05-07 14:42 UTC
**Describe the bug**
In the enemies lore, there is a `// Shield` with `// Description of the enemy` description.

**To Reproduce**
1. Go to Field Notes
2. Go to Enemies
3. See error

**Expected behavior**
A real name and description should show for this enemy.

**Screenshots**
https://imgur.com/ZCWpigK

**Desktop:**
 - OS: Windows 10
 - Nvidia RTX 2080

**Comment by ZinaDerudder** [comment] 2020-05-11 13:22
Duplicate of #129

**Closed as completed by ZinaDerudder** 2020-05-11 13:22 UTC
Labels: duplicate
