### ISSUE TITLE
Beat the arena fight, but the gate is still there?

### ISSUE THREAD

**Issue by kantra19** [FishingCactus/NanotaleEarlyAccessBugs#26] opened 2019-10-24 23:58 UTC
![20191024195035_1](https://user-images.githubusercontent.com/56983552/67533585-93676700-f698-11e9-9e63-d528263cbd5a.jpg)
![20191024195045_1](https://user-images.githubusercontent.com/56983552/67533588-95312a80-f698-11e9-8aee-58a28326329b.jpg)

I beat this arena fight (it glitched out, but it's over, and I can't restart it), but this gate is still here. I assume it was supposed to go away?

**Comment by xNightAngelx** [comment] 2019-10-26 03:16
Yep, this happened to me too, I had to restart the game many time due to this bug. This also happens at the third arena fight. So, I advice you to hold on to playing the game for a while...(I'll avoid spoilers so I won't put up any screenshots)

**Comment by brunourbain** [comment] 2019-10-26 12:49
Duplicate of #31 Locking down the thread.

**Comment by brunourbain** [comment] 2019-10-26 12:50
Yes  it was supposed to go away.

**Closed as completed** 2019-10-30 14:03 UTC
Labels: bug, duplicate, sometimes
